## Raw code(Min, Max Normalization)

In [132]:
def min_max_scaling(data):
    min_value= min(data)
    max_value= max(data)
    scaled_data= [(x - min_value)/(max_value - min_value) for x in data]
    return scaled_data

In [133]:
data=[1,20,30,4,5]
Scaled_data= min_max_scaling(data)
print("orginal data:",data)
print("Scaled_data(raw):",Scaled_data)

orginal data: [1, 20, 30, 4, 5]
Scaled_data(raw): [0.0, 0.6551724137931034, 1.0, 0.10344827586206896, 0.13793103448275862]


## Using sklearn

In [134]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [135]:
data={"feature1":[1,20,23,6,7,12],
      "feature2":[2,5,22,14,19,5]}

In [136]:
df=pd.DataFrame(data)
df

feature1  feature2
0         1         2
1        20         5
2        23        22
3         6        14
4         7        19
5        12         5

In [137]:
scaler=MinMaxScaler()
scaled_data= scaler.fit_transform(df)
print("scaled_data:", scaled_data)

scaled_data: [[0.         0.        ]
 [0.86363636 0.15      ]
 [1.         1.        ]
 [0.22727273 0.6       ]
 [0.27272727 0.85      ]
 [0.5        0.15      ]]


## Standard scaling

In [138]:
import pandas as pd

In [139]:
data={"feature1":[1,20,23,6,7,12],
      "feature2":[2,5,22,14,19,5]}

In [140]:
df=pd.DataFrame(data)
df

feature1  feature2
0         1         2
1        20         5
2        23        22
3         6        14
4         7        19
5        12         5

In [141]:
def standarized_data(data):
    mean= data.mean()
    std_dev= data.std(ddof=0)
    standarized_data_raw= (data - mean)/ std_dev
    return standarized_data_raw

In [142]:
#standarized_df_raw= df.apply(standarized_data)
standarized_df_raw= standarized_data(df)

In [143]:
print("orginal dataframe:")
print(df)
print("standarized data:")
print(standarized_df_raw )

orginal dataframe:
   feature1  feature2
0         1         2
1        20         5
2        23        22
3         6        14
4         7        19
5        12         5
standarized data:
   feature1  feature2
0 -1.345306 -1.205665
1  1.089058 -0.811084
2  1.473431  1.424877
3 -0.704684  0.372660
4 -0.576560  1.030296
5  0.064062 -0.811084


In [144]:
standarized_df_raw.head()

feature1  feature2
0 -1.345306 -1.205665
1  1.089058 -0.811084
2  1.473431  1.424877
3 -0.704684  0.372660
4 -0.576560  1.030296

In [145]:
standarized_df_raw["feature1"].mean()+1

1.0

In [146]:
standarized_df_raw["feature1"].std()

1.0954451150103321

## sklearn

In [147]:
from sklearn.preprocessing import StandardScaler

In [148]:
scaler= StandardScaler()
standarized_data= scaler.fit_transform(df)
standarized_data=pd.DataFrame(standarized_data,columns=df.columns)
standarized_data

feature1  feature2
0 -1.345306 -1.205665
1  1.089058 -0.811084
2  1.473431  1.424877
3 -0.704684  0.372660
4 -0.576560  1.030296
5  0.064062 -0.811084

In [149]:
print("orginal data:")
print(df)
print("standarized data:")
print(standarized_df_raw )
print("standarized_data:")
print(standarized_data)

orginal data:
   feature1  feature2
0         1         2
1        20         5
2        23        22
3         6        14
4         7        19
5        12         5
standarized data:
   feature1  feature2
0 -1.345306 -1.205665
1  1.089058 -0.811084
2  1.473431  1.424877
3 -0.704684  0.372660
4 -0.576560  1.030296
5  0.064062 -0.811084
standarized_data:
   feature1  feature2
0 -1.345306 -1.205665
1  1.089058 -0.811084
2  1.473431  1.424877
3 -0.704684  0.372660
4 -0.576560  1.030296
5  0.064062 -0.811084


## fit,transform and fit_tranform

In [150]:
from IPython.display import Image
Image('minmax.png')

FileNotFoundError: No such file or directory: 'minmax.png'

FileNotFoundError: No such file or directory: 'minmax.png'

<IPython.core.display.Image object>

In [151]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

## Generate some example data¶

In [152]:
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

## Create a MinMaxScaler instance

In [153]:
scaler = MinMaxScaler()

## Fit the scaler to the data and transform it in one step

In [154]:
data_transformed = scaler.fit_transform(data)
data_transformed

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

## Alternatively, you can use fit and transform separately¶

In [155]:
scaler.fit(data)
data_transformed_separate = scaler.transform(data)

## Print the original data, transformed data using fit_transform, and transformed data using fit and transform separately¶

In [156]:
print("Original Data:")
print(data)

print("\nTransformed Data using fit_transform:")
print(data_transformed)

print("\nTransformed Data using fit and transform separately:")
print(data_transformed_separate)


Original Data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Transformed Data using fit_transform:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]

Transformed Data using fit and transform separately:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


## Fit and Transform Seperately¶

In [157]:
scaler.fit(data)
data_transformed_separate = scaler.transform(data)

In [158]:
print("Original Data:")
print(data)

print("\nTransformed Data using fit and transform separately:")
print(data_transformed_separate)

Original Data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Transformed Data using fit and transform separately:
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
