In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
import seaborn as sns
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [23]:
House_price_dataset= pd.read_csv("House_price_data.csv")
House_price_dataset.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [24]:
X= House_price_dataset.iloc[:,2:10].values
y= House_price_dataset.iloc[:,1].values
y = [int(label) for label in y] 

In [25]:
from pandas.core.common import random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,random_state = 0)

In [26]:
print(X_train)

[[4.00e+00 2.50e+00 2.55e+03 ... 0.00e+00 0.00e+00 3.00e+00]
 [5.00e+00 2.75e+00 3.19e+03 ... 0.00e+00 3.00e+00 3.00e+00]
 [4.00e+00 2.00e+00 2.51e+03 ... 0.00e+00 0.00e+00 4.00e+00]
 ...
 [5.00e+00 2.75e+00 2.08e+03 ... 0.00e+00 0.00e+00 3.00e+00]
 [4.00e+00 2.50e+00 3.07e+03 ... 0.00e+00 3.00e+00 4.00e+00]
 [3.00e+00 1.75e+00 1.70e+03 ... 0.00e+00 0.00e+00 3.00e+00]]


In [27]:
print(y_train)

[537500, 1030000, 581000, 450000, 613000, 280000, 309000, 492000, 1506000, 760000, 830000, 486445, 408000, 355000, 427874, 350000, 330000, 200000, 364900, 458000, 198995, 405000, 369950, 367500, 763101, 850000, 321500, 558000, 290300, 700000, 383000, 1157200, 539000, 315000, 512500, 230000, 905000, 453500, 575000, 519950, 275000, 549000, 251000, 585000, 549000, 1225000, 440000, 385000, 406500, 758000, 645000, 445838, 535000, 995000, 0, 1738000, 299950, 1150000, 1100000, 840000, 0, 738500, 330000, 551000, 530000, 560000, 330000, 299950, 295000, 550000, 775000, 1695000, 765000, 345000, 749950, 435000, 567500, 494400, 280500, 935000, 615000, 205000, 330000, 258125, 490000, 240000, 520000, 550000, 405000, 607500, 218000, 195000, 546000, 584000, 377500, 625000, 220000, 548000, 284000, 310000, 823000, 525000, 282000, 631500, 253000, 402000, 335000, 373000, 615000, 263000, 320000, 300000, 320000, 2321000, 245000, 430277, 743700, 1035000, 430000, 883000, 252500, 345000, 930000, 851000, 576000,

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
from sklearn.svm import SVC
classifier= SVC(kernel='linear',random_state = 0)
classifier.fit(X_train,y_train) 

SVC(kernel='linear', random_state=0)

In [30]:
## accauracy on training set
X_train_prediction= classifier.predict(X_train)
X_train_prediction
training_accuracy_score= accuracy_score(y_train,X_train_prediction)
print(training_accuracy_score)

0.06869565217391305
